%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\kevin\Documents\Projects\LFAST\LFAST_Repos\PMC_GUI_V2\PMC_GUI\tables\TEC_centroids.csv
%
% Auto-generated by MATLAB on 01-Sep-2023 09:02:49

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 3, "Encoding", "UTF-8");

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["TEC", "Xm", "Ym"];
opts.VariableTypes = ["double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
tbl = readtable("C:\Users\kevin\Documents\Projects\LFAST\LFAST_Repos\PMC_GUI_V2\PMC_GUI\tables\TEC_centroids.csv", opts);

%% Convert to output type
TEC = tbl.TEC;
Xm = tbl.Xm;
Ym = tbl.Ym;

%% Clear temporary variables
clear opts tbl

%% Generate M1 Config
[theta, rho] = cart2pol(Xm, Ym);
enabled = ones(size(theta));
polar_coords_tbl = table(TEC, theta, rho, enabled, 'VariableNames',{'TEC', 'theta', 'rho', 'enabled'});
writetable(polar_coords_tbl, 'M1_Config.csv', 'Delimiter', ',')

%% Generate M1 command CSV (with arbitrary commands - just for debugging)
cmd = 2*rand(size(TEC))-1;
cmd_tbl = table(TEC, cmd, enabled, 'VariableNames',{'TEC', 'cmd', 'enabled'});
writetable(cmd_tbl, 'test_cmds.csv', 'Delimiter', ',')